using System;
using FiresCore.Logging;
using UnityEngine;

namespace VerdantsAscent
{
    // FiresVAngarde's console banners, rendered through the shared Banner engine.
    //
    //   PrintBig()  → eye-emblem watch shield with the FIRES VANGARDE brand.
    //                 Fires at the very top of Awake as the load announcement.
    //   Print()     → compact watch shield over a status frame ("WATCH POSTED").
    //                 Fires once when ZNetScene is ready (world load).
    //
    // Art generated by Tools\gen_fires_banner.ps1 (spec: FiresVAngarde).
    // Color zones: shield field (Red/DarkRed), watch eye (Red/DarkRed on dots),
    // steel base (DarkGray), brand (Red/White), compact eye (Cyan).
    internal static class FiresVAngardeBanner
    {
        private static bool s_compactPrinted;

        public static void PrintBig()
        {
            try
            {
                EmitHeader("Fires VAngarde Loading...");
                Banner.Print(ToSegments(s_bigLines));
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresVAngarde] Big banner failed: {ex.Message}");
            }
        }

        public static void Print()
        {
            if (s_compactPrinted) return;
            s_compactPrinted = true;
            try
            {
                EmitHeader("Fires VAngarde Loaded.");
                Banner.Print(s_compactLines);
            }
            catch (Exception ex)
            {
                Debug.LogWarning($"[FiresVAngarde] Compact banner failed: {ex.Message}");
            }
        }

        // Routes the one-line header through the plugin's BepInEx log source so it
        // prints once (and reaches LogOutput.log on headless) without a raw white
        // stdout duplicate. Falls back to Debug.Log before Awake wires the source.
        private static void EmitHeader(string text)
        {
            if (FiresVAngarde.Log != null) FiresVAngarde.Log.LogInfo(text);
            else Debug.Log($"[FiresVAngarde] {text}");
        }

        private static Banner.Segment[][] ToSegments((string text, ConsoleColor color)[] lines)
        {
            var result = new Banner.Segment[lines.Length][];
            for (int i = 0; i < lines.Length; i++)
                result[i] = new[] { new Banner.Segment(lines[i].text, lines[i].color) };
            return result;
        }

        // Compact banner — watch shield over a status frame. 31-char frame body
        // (3 lead + ╔ + 26 ═ + ╗). 🏛 is a surrogate pair, but the console ADVANCES ONE column for it: it is a
        // text-presentation emoji with no VS16, so it is padded as one cell however wide the font paints it.
        // Every Fires banner had this row a column short from assuming two.
        private static readonly Banner.Segment[][] s_compactLines =
        {
            new[] { new Banner.Segment("            ╔═══════╗",        ConsoleColor.DarkGray) },
            new[]
            {
                new Banner.Segment("            ║",   ConsoleColor.DarkGray),
                new Banner.Segment("██ ",             ConsoleColor.DarkRed),
                new Banner.Segment("◉",               ConsoleColor.Cyan),
                new Banner.Segment(" ██",             ConsoleColor.DarkRed),
                new Banner.Segment("║",               ConsoleColor.DarkGray),
            },
            new[]
            {
                new Banner.Segment("            ╚═",  ConsoleColor.DarkGray),
                new Banner.Segment("█████",           ConsoleColor.DarkRed),
                new Banner.Segment("═╝",              ConsoleColor.DarkGray),
            },
            new[] { new Banner.Segment("              ╲███╱",          ConsoleColor.Red) },
            new[] { new Banner.Segment("               ╲█╱",           ConsoleColor.DarkRed) },
            new[] { new Banner.Segment("   ╔══════════════════════════╗", ConsoleColor.DarkGray) },
            new[]
            {
                new Banner.Segment("   ║   ",              ConsoleColor.DarkGray),
                new Banner.Segment("[",                    ConsoleColor.Gray),
                new Banner.Segment("██████████████████",   ConsoleColor.Green),
                new Banner.Segment("]",                    ConsoleColor.Gray),
                new Banner.Segment("   ║",                 ConsoleColor.DarkGray),
            },
            new[]
            {
                new Banner.Segment("   ║     ",            ConsoleColor.DarkGray),
                new Banner.Segment("🏛 WATCH POSTED",      ConsoleColor.Yellow),
                // Seven spaces, not six: the console advances ONE column for a text-presentation emoji like this one
                // (no VS16), while the row was laid out as if it took two, leaving the right bar a column short.
                new Banner.Segment("       ║",             ConsoleColor.DarkGray),
            },
            new[] { new Banner.Segment("   ╚══════════════════════════╝", ConsoleColor.DarkGray) },
            new[] { new Banner.Segment("    FIRES VANGARDE",           ConsoleColor.Cyan) },
            new Banner.Segment[0],
            new[] { new Banner.Segment("   Fires VAngarde Loaded",     ConsoleColor.Magenta) },
        };

        private static readonly (string text, ConsoleColor color)[] s_bigLines =
        {
            ("", ConsoleColor.Gray),
            ("%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%@%%%%@%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%@%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=::-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=::-%%%%%@%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%@%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=::-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%@%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=::-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%", ConsoleColor.Red),
            ("%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:::::::::::::::*@%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%@%@%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%-:::::::::::::::*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%******=::-******#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=::-%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:...................................*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%:...................................*%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%:...................................*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:...................................*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:...................................*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%@%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%:...................................*%%%@%@@%%%%%%%%%%%%%%%%@%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:...................................*%%%%@%%%%%%%%%%%%%%%%%@%%%%%%%@", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:..........::----------::...........*@%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%:........:-%%%%%----%%%%%-::........*%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%:......:-%%%%%%:....:-%%%%%-:.......*%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%@%%%%%%%@%%%%%%%%%:.....:+%@%%%%-..::..:%%%%%%%:......*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:.....-%%%%%%%:.:%%:..*%%@%%%*......*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%:.....-%%%%%%%:.:%%:..*%%%%%%%......*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:.....:%%%%%%%:..::..:%%%%%%%-......*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@", ConsoleColor.DarkRed),
            ("%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%:......:-%%%%%+:....:-%%%%%%-.......*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%:.......:--%%%%%-::-=%%%%--:........*%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%@%%%%%%%%%%%%%%%%%%%%@%%%%%%%:..........::---@%%%*---:...........*@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%-..................................:*%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:..............................:-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*:............................:-%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%-:.........................-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%-:......................:-%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-....................:-%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-:.................-%%%%%%%%%%%@%%@%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%=:..............:-%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%@%@%%%%%%%@%%%%%%%%%%%%%%%%%%%%@%-:...........:@%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%@@%%%%%%%%%%%%%%%%%%%%%-:........:-%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%-......:-%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkRed),
            ("%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%-:...-%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%@@%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%-::-%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%@%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%@%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%@%%%%%%%%%%%%%%@%%@%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%@%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%", ConsoleColor.DarkGray),
            ("%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%@%%%%@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%@%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%-::::#%::::-%-::::::%%%::::-%-:::%@%-::.:::-%%%%:::::::%%%::::::::-%%-::::::::-%@-:::::::%%%%%%", ConsoleColor.Red),
            ("%%%%%-....--....:%:......-%%:...:%:...%%:........:%%=.......%%%.........-%-.........-@:......:%%%%%%", ConsoleColor.White),
            ("%%%%%#....:-....-%.......:%%:....::...%@....--....%%-.......-%%....-:...:%-....%:...:%:....%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%:...::....%-...:....%%:.....:...%%....--::::%%:...:...:%%....::...:%-....%:...:%:....::-%%%%%%", ConsoleColor.White),
            ("%%%%%%:....:...:@:...-:...-%:.........%%....-.....%%....*...:%%........:-%-....%:...:%:......:%%@%%%", ConsoleColor.Red),
            ("%%%%%%-........-%:...::...:%:...:.....%%....-:....%-....-....+%....-:...:%-....%:...:%:....---%%%%%%", ConsoleColor.White),
            ("%%%%%%%:.......+#.........:%:...-.....%%....--....%:.........-%....--...:%-....%:...:@:....%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%:......:%-....-:....*:...%:....%%:....:....%:...:-:...:%....--...:%-.........:%:.......#%%%%%", ConsoleColor.White),
            ("%%%%%%%-::::::-%-::::%=::::-::::%*::::%%@-:..:-:::%::::-%-::::%::::--::::%-::::::::-#%-:::::::#%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%", ConsoleColor.White),
            ("@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%@%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.White),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.Red),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%@%%%@%%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%%%%%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%%%@%%%%%%%%%%%%%%%%%", ConsoleColor.DarkGray),
            ("%%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%@%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@%@%@%", ConsoleColor.DarkGray),
            ("", ConsoleColor.Gray),
        };
    }
}
